// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azswoucomvqimtqzkqko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6c3dvdWNvbXZxaW10cXprcWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzA2MzQsImV4cCI6MjA3NDA0NjYzNH0.OUlWjt7axrlsfSXFWJx_f-F7ClnOpKfLWvEe6DVqI9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});